<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3cs_sessions"
 *
 * Auto generated by Extension Builder 2015-05-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Sessions',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Thomas Löffler',
    'author_email' => 'loeffler@spooner-web.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.4.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
